@host = http://127.0.0.1:8001
@aws_sns = {{$dotenv AWS_SERVER_ENDPOINT}}
POST {{host}}/fetch
Content-Type: application/json

{
    "fetch_list": [
        {
            "type": "github",
            "repository":   "HomeSmartMesh/website",
            "ref":  "main",
            "path": "repos",
            "filter":   "content/3dprinting/**/*"
        }
    ]
}

### test post sns
POST {{aws_sns}}
Content-Type: application/json

{
    "test": "check"
}
