services:
  diagrams-viewer:
    build:
      context: ./diagrams-viewer
      args:
        KROKI_RENDERER_URL: https://localhost:7040/
    ports:
      - 9000:80
    depends_on:
      - kroki
    profiles: ["diagrams"]
  fetcher:
    build: ./fetcher
    volumes:
      - ./cache/fetch:/cache/fetch
      - ./common/utils:/common/utils
    environment:
      - BROKER=mosquitto
    depends_on:
      - mosquitto
    profiles: ["events"]
  markdown:
    build: ./markdown
    volumes:
      - ./cache/fetch:/fetch
      - ./cache/process:/process
      - ./cache/web:/web
      - ./common/utils:/common/utils
    environment:
      - BROKER=mosquitto
    depends_on:
      - mosquitto
    profiles: ["events"]
  mosquitto:
    build: ./mosquitto
    ports:
      - 1883:1883
    volumes:
      - ./cache/log/mosquitto:/mosquitto/log
  nginx:
    build: ./nginx
    volumes:
      - ./certs:/etc/nginx/certs
    ports:
      - 443:443
      - 4040:4040
      - 7040:7040
    depends_on:
      - mermaid-live-editor
      - viewer
      - kroki
    profiles: ["diagrams"]
  runner:
    build: ./runner
    volumes:
      - ./workflow.yaml:/app/workflow.yaml
    environment:
      - BROKER=mosquitto
    depends_on:
      - mosquitto
      - fetcher
      - markdown
      - search
  search:
    build: ./search
    volumes:
      - ./cache/process:/cache/process
      - ./common/utils:/common/utils
    environment:
      - BROKER=mosquitto
      - SEARCH_HOST=typesense
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
    depends_on:
      - mosquitto
      - typesense
    profiles: ["events"]
  typesense:
    image: typesense/typesense:26.0
    restart: on-failure
    ports:
      - 8108:8108
    volumes:
      - ./cache/data/typesense:/data
    environment:
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
    command: '--data-dir /data --enable-cors'
  kroki:
    image: yuzutech/kroki
    ports:
      - 7000:8000
    environment:
      - KROKI_BLOCKDIAG_HOST=blockdiag
      - KROKI_MERMAID_HOST=mermaid
      - KROKI_BPMN_HOST=bpmn
      - KROKI_DIAGRAMSNET_HOST=diagramsnet
    depends_on:
      - blockdiag
      - mermaid
      - bpmn
    profiles: ["diagrams"]
  blockdiag:
    image: yuzutech/kroki-blockdiag
    profiles: ["diagrams"]
  mermaid:
    image: yuzutech/kroki-mermaid
    profiles: ["diagrams"]
  bpmn:
    image: yuzutech/kroki-bpmn
    profiles: ["diagrams"]
  diagramsnet:
    image: yuzutech/kroki-diagramsnet
    profiles: ["diagrams"]
