@cloud_ip={{$dotenv CLOUD_IP}}
GET http://localhost:6000/fetch
Content-Type: application/json

{
    "test": "request"
}

###test cloud
GET http://{{cloud_ip}}:6000/fetch
Content-Type: application/json

{
    "test": "request"
}
